"""test creation of db tables

Revision ID: 339d8872128e
Revises: b3ed2dc143be
Create Date: 2026-02-12 22:10:50.331620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '339d8872128e'
down_revision: Union[str, None] = 'b3ed2dc143be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('amount_sgd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('item', sa.String(), nullable=False),
    sa.Column('channel', sa.Enum('Online', 'Offline', name='transactionchannel'), nullable=False),
    sa.Column('category', sa.Enum('Food', 'Travel', 'Shopping', 'Bills', 'Entertainment', 'Others', name='transactioncategory'), nullable=True),
    sa.Column('is_overseas', sa.Boolean(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card_catalogue.card_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
