"""create card_catalogue table

Revision ID: 6223ac20df34
Revises: c9e4a2a7d1b0
Create Date: 2026-02-15 17:28:53.742337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6223ac20df34'
down_revision: Union[str, None] = 'c9e4a2a7d1b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_catalogue',
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('bank', sa.Enum('DBS', 'CITI', 'Standard_Chartered', name='bankenum'), nullable=False),
    sa.Column('card_name', sa.String(length=255), nullable=False),
    sa.Column('benefit_type', sa.Enum('MILES', 'CASHBACK', 'BOTH', name='benefittypeenum'), nullable=False),
    sa.Column('base_benefit_rate', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('status', sa.Enum('VALID', 'INVALID', name='statusenum'), nullable=False),
    sa.CheckConstraint('base_benefit_rate >= 0', name='ck_base_benefit_rate_non_negative'),
    sa.PrimaryKeyConstraint('card_id'),
    sa.UniqueConstraint('bank', 'card_name', name='uq_bank_card_name')
    )
    op.create_index(op.f('ix_card_catalogue_card_id'), 'card_catalogue', ['card_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_card_catalogue_card_id'), table_name='card_catalogue')
    op.drop_table('card_catalogue')
    # ### end Alembic commands ###
