"""add_total_reward_to_transactions

Revision ID: 7bbdf9649f2c
Revises: ec4a6dd546f7
Create Date: 2026-03-10 12:18:15.331122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bbdf9649f2c'
down_revision: Union[str, None] = 'ec4a6dd546f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('total_reward', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'total_reward')
    # ### end Alembic commands ###
