"""Add status field to transactions

Revision ID: 8e6d0b130081
Revises: 9f2c1b3e4a5d
Create Date: 2026-02-20 21:00:57.962632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e6d0b130081'
down_revision: Union[str, None] = '9f2c1b3e4a5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card_bonus_category', 'bonus_cap_in_dollar',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('card_bonus_category', 'bonus_minimum_spend_in_dollar',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('card_catalogue', 'bank',
               existing_type=sa.VARCHAR(length=17),
               type_=sa.Enum('DBS', 'CITI', 'Standard_Chartered', 'UOB', name='bankenum'),
               existing_nullable=False)
    op.add_column('transactions', sa.Column('status', sa.Enum('Active', 'DeletedWithCard', name='transactionstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'status')
    op.alter_column('card_catalogue', 'bank',
               existing_type=sa.Enum('DBS', 'CITI', 'Standard_Chartered', 'UOB', name='bankenum'),
               type_=sa.VARCHAR(length=17),
               existing_nullable=False)
    op.alter_column('card_bonus_category', 'bonus_minimum_spend_in_dollar',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('card_bonus_category', 'bonus_cap_in_dollar',
               existing_type=sa.INTEGER(),
               server_default=sa.text('(99999999)'),
               existing_nullable=False)
    # ### end Alembic commands ###
