"""Add status field to transactions

Revision ID: 8e6d0b130081
Revises: 9f2c1b3e4a5d
Create Date: 2026-02-20 21:00:57.962632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e6d0b130081'
down_revision: Union[str, None] = '9f2c1b3e4a5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('status', sa.Enum('Active', 'DeletedWithCard', name='transactionstatus'), nullable=False, server_default='Active'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'status')
    # ### end Alembic commands ###
