"""update tables in database

Revision ID: abace054452a
Revises: 339d8872128e
Create Date: 2026-02-12 23:45:41.434201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abace054452a'
down_revision: Union[str, None] = '339d8872128e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_spending_id', table_name='user_spending')
    op.drop_table('user_spending')
    op.add_column('user_owned_cards', sa.Column('billing_cycle_refresh_date_of_mth', sa.Integer(), nullable=False))
    op.drop_column('user_owned_cards', 'billing_cycle_refresh_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_owned_cards', sa.Column('billing_cycle_refresh_date', sa.DATETIME(), nullable=False))
    op.drop_column('user_owned_cards', 'billing_cycle_refresh_date_of_mth')
    op.create_table('user_spending',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('card_id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('category', sa.VARCHAR(length=13), nullable=True),
    sa.Column('spending_date', sa.DATE(), nullable=False),
    sa.Column('created_date', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_spending_id', 'user_spending', ['id'], unique=False)
    # ### end Alembic commands ###
