"""update tables in database

Revision ID: abace054452a
Revises: 339d8872128e
Create Date: 2026-02-12 23:45:41.434201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abace054452a'
down_revision: Union[str, None] = '339d8872128e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_owned_cards', sa.Column('billing_cycle_refresh_date_of_mth', sa.Integer(), nullable=False))
    op.drop_column('user_owned_cards', 'billing_cycle_refresh_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_owned_cards', sa.Column('billing_cycle_refresh_date', sa.DATETIME(), nullable=False))
    op.drop_column('user_owned_cards', 'billing_cycle_refresh_date_of_mth')
    # ### end Alembic commands ###
