"""Create user profile, user owned cards and user spending tables

Revision ID: b3ed2dc143be
Revises: 
Create Date: 2026-02-12 05:41:49.923087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3ed2dc143be'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_catalogue',
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('bank', sa.Enum('DBS', 'Citi', 'StandardChartered', name='bankenum'), nullable=False),
    sa.Column('card_name', sa.String(length=255), nullable=False),
    sa.Column('benefit_type', sa.Enum('Miles', 'Cashback', 'BOTH', name='benefittypeenum'), nullable=False),
    sa.Column('base_benefit_rate', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('status', sa.Enum('valid', 'invalid', name='statusenum'), nullable=False),
    sa.CheckConstraint('base_benefit_rate >= 0', name='ck_base_benefit_rate_non_negative'),
    sa.PrimaryKeyConstraint('card_id'),
    sa.UniqueConstraint('bank', 'card_name', name='uq_bank_card_name')
    )
    op.create_index(op.f('ix_card_catalogue_card_id'), 'card_catalogue', ['card_id'], unique=True)
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('benefits_preference', sa.Enum('Miles', 'Cashback', 'No_preference', name='benefitspreference'), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_user_profile_id'), 'user_profile', ['id'], unique=False)
    op.create_table('user_owned_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('card_expiry_date', sa.DateTime(), nullable=False),
    sa.Column('billing_cycle_refresh_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('Active', 'Inactive', 'Closed', name='userownedcardstatus'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card_catalogue.card_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_owned_cards_id'), 'user_owned_cards', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_owned_cards_id'), table_name='user_owned_cards')
    op.drop_table('user_owned_cards')
    op.drop_index(op.f('ix_user_profile_id'), table_name='user_profile')
    op.drop_table('user_profile')
    op.drop_index(op.f('ix_card_catalogue_card_id'), table_name='card_catalogue')
    op.drop_table('card_catalogue')
    # ### end Alembic commands ###
