"""add billing_refresh_day_of_mth

Revision ID: ec4a6dd546f7
Revises: d4e5f6a7b8c9
Create Date: 2026-03-09 19:38:52.377049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec4a6dd546f7'
down_revision: Union[str, None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_owned_cards', sa.Column('billing_cycle_refresh_day_of_mth', sa.Integer(), nullable=False, server_default="1"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_owned_cards', 'billing_cycle_refresh_day_of_mth')
    # ### end Alembic commands ###
