"""update tables in database

Revision ID: f57061b2a41c
Revises: abace054452a
Create Date: 2026-02-13 00:04:15.335921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f57061b2a41c'
down_revision: Union[str, None] = 'abace054452a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_owned_cards', sa.Column('billing_cycle_refresh_date', sa.DateTime(), nullable=False))
    op.drop_column('user_owned_cards', 'billing_cycle_refresh_date_of_mth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_owned_cards', sa.Column('billing_cycle_refresh_date_of_mth', sa.INTEGER(), nullable=False))
    op.drop_column('user_owned_cards', 'billing_cycle_refresh_date')
    # ### end Alembic commands ###
